import Head from "next/head";
import { Fragment } from "react";
import ProductGrid from "../components/ProductGrid/ProductGrid";
import PageLayout from "../components/UI/PageLayout/PageLayout";

const pageHeadData = {
    category: "12 x 12",
    collection: "All Products",
};

export default function Home() {
    return (
        <Fragment>
            <Head>
                <title>Astro Vinyl Art</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <PageLayout>
                <ProductGrid />
            </PageLayout>
        </Fragment>
    );
}
