import Head from "next/head";
import { Fragment } from "react";
import ProductGrid from "../components/ProductGrid/ProductGrid";
import HomeDisplay from "../components/UI/HomeDisplay/HomeDisplay";
import PageLayout from "../components/UI/PageLayout/PageLayout";

import vinyl from "./../public/vinyl.png";

const pageHeadData = {
    category: "12 x 12",
    collection: "All Products",
};

const productArray = [
    {
        name: "2pac",
        price: 50,
        imgUrl: vinyl,
    },
    {
        name: "Beatles",
        price: 50,
        imgUrl: vinyl,
    },
    {
        name: "ACDC",
        price: 50,
        imgUrl: vinyl,
    },
    {
        name: "Biggie",
        price: 50,
        imgUrl: vinyl,
    },
];

export default function Home() {
    return (
        <Fragment>
            <Head>
                <title>Astro Vinyl Art</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HomeDisplay />
            {/* <PageLayout>
                <ProductGrid productArray={productArray} />
            </PageLayout> */}
        </Fragment>
    );
}
